### ISSUE TITLE
Sometimes AmongUs can't start(Null error)

### ISSUE THREAD

**Issue by yukieiji** [SubmergedAmongUs/Submerged#33] opened 2022-06-11 15:46 UTC
**Describe the bug**
Sometimes AmongUs can't start

**To Reproduce**
1. Launching AmongUs

**Expected behavior**
AmongUs stop during loading

**Screenshots**
error with console:
![nullError](https://user-images.githubusercontent.com/40425798/173194786-f665f662-672b-4d62-a7d1-6b432c0adf43.PNG)

stop this screen:
![LunchLoop](https://user-images.githubusercontent.com/40425798/173194835-4cbe58de-c5e0-46c7-be2d-c22b21f7d0a4.PNG)

**Version (please complete the following information):**
 - Among Us: 2022.4.19e
 - Submerged:  2022.5.20
 - BeplnEx : 6.0.0 - be.565(with my mod, I get an error with be.562)

**Log file**
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/8884252/LogOutput.log)

**Comment by AlexejheroYTB** [comment] 2022-06-12 08:08
This issue is a duplicate of #28

**Closed by AlexejheroYTB** 2022-06-12 08:08 UTC
Labels: bug
