### ISSUE TITLE
Bugs at the beginning of the game and on voting 

### ISSUE THREAD

**Issue by ArslanShakirov** [SubmergedAmongUs/Submerged#85] opened 2023-06-23 17:15 UTC
![20230623215057_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/5a92c600-b660-40af-be7e-9f43610b29dc)
![20230623215154_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/19f4f496-2381-4b12-84bc-573e1b590ae7)
![20230623221059_1](https://github.com/SubmergedAmongUs/Submerged/assets/117534959/076b83ad-683d-44a4-bf37-1f14d39c8ffa)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Among Us: [e.g. 2023.3.29s]
 - Submerged: [e.g. 2023.4.9s]

**Log file**
Please attach the log file located in BepInEx/LogOutput.log
If you have restarted your game since you last encountered the issue, please try to reproduce the issue again and then upload the log.

**Additional context**

**Comment by ArslanShakirov** [comment] 2023-06-23 17:16
P.S Translate: Защита - Protect

**Comment by Alexejhero** [comment] 2023-06-23 17:17
Could you please describe what the issues are?

Also, please attach the log file located in your Among Us folder, in `BepInEx/LogOutput.log`
If you have restarted your game since you last encountered the issue, please try to reproduce the issue again and then upload the log.

**Comment by ArslanShakirov** [comment] 2023-06-23 17:19
[LogOutput.log](https://github.com/SubmergedAmongUs/Submerged/files/11850756/LogOutput.log)

**Comment by ArslanShakirov** [comment] 2023-06-23 17:22
> Could you please describe what the issues are?
> 
> Also, please attach the log file located in your Among Us folder, in If you have restarted your game since you last encountered the issue, please try to reproduce the issue again and then upload the log.`BepInEx/LogOutput.log`

the chat is on during the uploading process and on the votes before the corpses are shown the chat is on

**Comment by ArslanShakirov** [comment] 2023-06-23 17:27
also on the voting tasks are displayed and the protect button on the voting is displayed

**Comment by NetherDragonTw** [comment] 2023-06-24 12:57
i'll try to explain what he says.
first, at game beginning's black screen, the chat button was appear(in vanilla, the chat button shouldn't show up at this time.)
second, at voting starting the chat button was appear quickly as voting UI show up.(in vanilla, the chat button should show up at the voting UI show ups.)

**Comment by ArslanShakirov** [comment] 2023-06-24 16:49
> Я попытаюсь объяснить, что он говорит. во-первых, в начале игры на черном экране появлялась кнопка чата (в ванили кнопка чата не должна отображаться в это время). во-вторых, при запуске голосования кнопка чата появлялась быстро, когда отображался интерфейс голосования (в ванили). , кнопка чата должна отображаться в интерфейсе голосования.)

Yes

**Comment by Alexejhero** [comment] 2023-06-28 00:53
I haven't been able to reproduce this issue

**Comment by Sand-and-Beans** [comment] 2023-07-05 07:35
Yeah I have this issue too

**Comment by Alexejhero** [comment] 2023-07-05 10:19
Are we sure this isn't a problem from base game? This mod doesn't really touch meetings or the chat or anything...

**Comment by ArslanShakirov** [comment] 2023-07-05 10:22
> Are we sure this isn't a problem from base game? This mod doesn't really touch meetings or the chat or anything...

no

**Comment by ArslanShakirov** [comment] 2023-07-05 10:23
without this mod there are no bugs with chat and voting

**Comment by Tommy-XL** [comment] 2023-07-05 11:02
I think this is happening because other players don't have the Submerged mod installed

**Comment by tartsharpcobra** [comment] 2023-07-05 13:17
Veryyyy precise description.

**Comment by Alexejhero** [comment] 2023-07-05 16:45
> I think this is happening because other players don't have the Submerged mod installed

I don't think that's the reason...

**Comment by Sand-and-Beans** [comment] 2023-07-07 14:21
> Are we sure this isn't a problem from base game? This mod doesn't really touch meetings or the chat or anything...

Nope I think. I tried the vanilla game but there is no this bug.

**Comment by Alexejhero** [comment] 2023-07-09 09:39
This will be fixed in the next update. Thank you for the help.

**Closed by Alexejhero** 2023-07-09 09:39 UTC
Labels: bug
