### ISSUE TITLE
Fix Wiring has gap in wires

### ISSUE THREAD

**Issue by Endrmen40487** [SubmergedAmongUs/Submerged#32] opened 2022-06-08 01:37 UTC
Among Us version:2022.3.29
Submerged version:2022.5.20

2.In fix wiring task, some white square are in front of wire.

![螢幕擷取畫面 (120)](https://user-images.githubusercontent.com/105161305/172512101-b27f3c81-27cb-4f78-b141-724fbd2f9acb.png)

(My English is very bad)
<details>
<summary>Outdated</summary>
1.In start submersible task, you don't need turn key, you can open anything about this task. 

![螢幕擷取畫面 (121)](https://user-images.githubusercontent.com/105161305/172512110-c2683596-20ed-48b6-87d1-6c80efd7d780.png)

3.Some shadow area, texture's picture quality is very low.

![螢幕擷取畫面 (122)](https://user-images.githubusercontent.com/105161305/172512625-d862f627-30e3-49ea-9c4b-b0b752a16f24.png)

![螢幕擷取畫面 2022-06-08 093637](https://user-images.githubusercontent.com/105161305/172512657-1c73106e-65fb-41e4-b729-91fca19f3623.png)

</details>

**Comment by AlexejheroYTB** [comment] 2022-06-08 04:55
1. This is intended behaviour
3. This is handled by Among Us and is out of our control.

**Comment by AlexejheroYTB** [comment] 2022-06-18 20:27
The wires issue will be fixed in the next version.

**Comment by AlexejheroYTB** [comment] 2022-06-23 22:52
Fixed in latest release.

**Closed by AlexejheroYTB** 2022-06-23 22:52 UTC
Labels: bug, resolved
