### ISSUE TITLE
Ghost of DeadPlayer Shown Thru Walls When Killed

### ISSUE THREAD

**Issue by Mr-Fluuff** [SubmergedAmongUs/Submerged#118] opened 2023-08-01 08:18 UTC
**Describe the bug**
When someone kills a player out of vision they see the ghost of the player for a split second as if this is a layering issue of some sort.

**To Reproduce**
Steps to reproduce the behavior: Tested On Every Map.
1. Put Crewmate A out of vision of Crewmate B
2. Kill Crewmate A
3. Crewmate B Sees ghost

**Expected behavior**
Should not see anything out of vision

**Screenshots**
![image](https://github.com/SubmergedAmongUs/Submerged/assets/79845185/6730dc4a-d22a-4f3c-b182-3c7113bc1a23)

**Version (please complete the following information):**
 - Among Us: v2023.7.12
 - Submerged: v2023.7.24

**Log file**
Please attach the log file located in BepInEx/LogOutput.log
If you have restarted your game since you last encountered the issue, please try to reproduce the issue again and then upload the log.

**Additional context**
Was looking at the submerged code and could not find anything that would cause this. I did uninstall submerged to see if it was a vanilla bug but everything was fine then.

**Comment by Sand-and-Beans** [comment] 2023-08-01 08:43
I think it is the vanilla game's bug, because I've met this while playing the vanilla game.

**Comment by Alexejhero** [comment] 2023-08-01 12:48
We had this issue before with Lifeboat and we fixed it in Lifeboat, I don't think it's Submerged related. I can't reproduce it with only Submerged installed without Stellar Roles.

**Comment by Mr-Fluuff** [comment] 2023-08-01 20:32
https://github.com/SubmergedAmongUs/Submerged/assets/79845185/515eafde-1270-4a3e-9741-af2a10464f23

**Comment by Alexejhero** [comment] 2023-08-01 20:49
That's weird, I wasn't able to reproduce it myself. I will look into it

**Comment by Alexejhero** [comment] 2023-08-02 11:11
Thanks for the report, the issue will be fixed in the next version

**Closed by Alexejhero** 2023-08-02 11:11 UTC
Labels: bug
